In [ ]:
import numpy as np

In [ ]:
ZeroD=np.array(46)
print(type(ZeroD))

<class 'numpy.ndarray'>


In [ ]:
oneD=np.array([12,45,89,47,45,78,89])
oneD

array([12, 45, 89, 47, 45, 78, 89])

In [ ]:
twoD=np.array([[12,12,25,45],[78,18,91,46],[4,8,9,4],[1,2,3,4]])
twoD

array([[12, 12, 25, 45],
       [78, 18, 91, 46],
       [ 4,  8,  9,  4],
       [ 1,  2,  3,  4]])

In [ ]:
ThreeD=np.array([[[1,8,4,6],[2,8,9,7],[4,6,8,3]]])
ThreeD

array([[[1, 8, 4, 6],
        [2, 8, 9, 7],
        [4, 6, 8, 3]]])

In [ ]:
np.ndim(twoD)

2

In [ ]:
np.size(twoD)

16

In [ ]:
np.shape(twoD)

(4, 4)

In [ ]:
print(type(ThreeD))

<class 'numpy.ndarray'>


In [ ]:
print(len(oneD))

7


In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(10,30,8)

array([10, 18, 26])

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.linspace(1,25,15)
np.linspace(4,50,7)

array([ 4.        , 11.66666667, 19.33333333, 27.        , 34.66666667,
       42.33333333, 50.        ])

In [ ]:
np.random.rand(4)

array([0.87255691, 0.59500106, 0.56283275, 0.25754124])

In [ ]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.random.randn(2)

array([-0.85797412,  0.79673565])